"""Example: python -m solar.predict --irradiation .7 --temperature 30 --hour 12"""
import argparse
import math
import joblib
import pandas as pd
from .train import predict

if __name__ == '__main__':
    parser=argparse.ArgumentParser(description='Estimate same-time Plant 1 AC power; use source sensor units.')
    parser.add_argument('--irradiation',type=float,required=True)
    parser.add_argument('--temperature',type=float,required=True)
    parser.add_argument('--hour',type=float,required=True)
    a=parser.parse_args()
    if not all(math.isfinite(v) for v in [a.irradiation,a.temperature,a.hour]) or a.irradiation < 0 or not 0 <= a.hour < 24:
        parser.error('Inputs must be finite, irradiation nonnegative, and hour in [0,24).')
    # Only load trusted artifacts generated by this project: joblib can execute code.
    bundle=joblib.load('models/solar.joblib')
    for name,value in [('IRRADIATION',a.irradiation),('AMBIENT_TEMPERATURE',a.temperature)]:
        low,high=bundle['ranges'][name]
        if not low <= value <= high:
            parser.error(f'{name} is outside training range [{low:.3f}, {high:.3f}].')
    frame=pd.DataFrame({'DATE_TIME':[pd.Timestamp('2020-06-01')+pd.Timedelta(hours=a.hour)], 'IRRADIATION':[a.irradiation], 'AMBIENT_TEMPERATURE':[a.temperature]})
    print(f"{bundle['name']}: {predict(bundle['model'],frame)[0]:,.1f} source AC_POWER units (Plant 1 estimate)")
